-- 코드를 작성해주세요
SELECT SUM(SCORE) as SCORE, e.EMP_NO, e.EMP_NAME, e.POSITION, e.EMAIL
FROM HR_EMPLOYEES e 
JOIN HR_GRADE g ON g.EMP_NO = e.EMP_NO
JOIN HR_DEPARTMENT d ON d.DEPT_ID = e.DEPT_ID
GROUP BY EMP_NO
ORDER BY SCORE DESC
LIMIT 1;